### PR TITLE
Card#47 java8 features code refactoring

### PR DESCRIPTION
**Pull request by fein91**
https://trello.com/c/lL4JCPc2/ 
i hope it works =) haven't check it yet

### CODE REVIEW

**Comment by fein91** [comment]
@xelamanster, @Grechka, @amakogon check this plz

**Comment by xelamanster** [comment]
You can pull method "mapToDtos" up to the interface (create default, remove duplicated implementations at each class). Public modifier in interface is redundant.

**Comment by fein91** [comment]
@xelamanster, updated, check plz

**Comment by xelamanster** [comment]
Looks ok.

**Pull request merged**
